version: '3'
services:
  backend:
    build: ./backend
    restart: unless-stopped
    # user: ${UID}:${GUID}
    volumes:
      - ./backend/mydiary:/usr/local/src/app/backend/mydiary
      - ./backend/scripts:/usr/local/src/app/backend/scripts
      - ./backend/alembic/versions:/usr/local/src/app/backend/alembic/versions
      - ./backend/notebooks:/usr/local/src/app/backend/notebooks
      - ./backend/poetry.lock:/usr/local/src/app/backend/poetry.lock
      - ./backend/pyproject.toml:/usr/local/src/app/backend/pyproject.toml
      - ./backend/token_cache:/usr/local/src/app/backend/token_cache
      - ./backend/tests:/usr/local/src/app/backend/tests
      - ./backend/pytest.ini:/usr/local/src/app/backend/pytest.ini
      - ./backend/cov.xml:/usr/local/src/app/backend/cov.xml
      # specify joplin data as a persistent docker volume (defined below)
      - joplin_data:/root/.config/joplin
      # use timezone information from host machine
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro 
    env_file:
      - ./backend/.env
    environment:
      # This ensures that errors are printed as they occur, which
      # makes debugging easier.
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=DEBUG
      - DEV_MODE=1
      # override these variables from the .env file:
      - SPOTIFY_TOKEN_CACHE_PATH=/usr/local/src/app/backend/token_cache/spotify.json
      - GOOGLECALENDAR_TOKEN_CACHE=/usr/local/src/app/backend/token_cache/googlecalendar_token.json
      - GOOGLECALENDAR_CREDENTIALS_FILE=/usr/local/src/app/backend/token_cache/googlecalendar_credentials.json
      - GOOGLEPHOTOS_TOKEN_CACHE=/usr/local/src/app/backend/token_cache/googlephotos_token.json
    # command: ["main:app", "--host", "0.0.0.0", "--reload"]
    # ports:
    #     - 8888:8888
  frontend:
    build: ./frontend
    # We can't mount the entire UI directory, since JavaScript dependencies
    # (`node_modules`) live at that location.
    restart: unless-stopped
    # user: ${UID}:${GUID}
    volumes:
      - ./frontend/src:/usr/local/src/app/frontend/src
      - ./frontend/public:/usr/local/src/app/frontend/public
      - ./frontend/build:/usr/local/src/app/frontend/build
      - ./frontend/package.json:/usr/local/src/app/frontend/package.json
      - ./frontend/tsconfig.json:/usr/local/src/app/frontend/tsconfig.json
      - ./frontend/yarn.lock:/usr/local/src/app/frontend/yarn.lock
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro 
      # use timezone information from host machine
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - NODE_ENV=development
    # ports:
    #     - 3000:3000
    depends_on:
      - backend
  proxy:
    image: nginx:1.17
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8085:80
    depends_on:
      - backend
      - frontend
    networks:
      - proxy-tier
      - default
  # cloudflared:
  #   image: cloudflare/cloudflared:2023.5.1
  #   # volumes: 
  #   #   - ./cloudflared:/etc/cloudflared
  #   # env_file:
  #   #   - ./cloudflared/cloudflared.env
  #   # command: 'tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN} --hello-world'
  #   # command: 'tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN} --url http://localhost:48916'
  #   # command: 'tunnel --no-autoupdate --loglevel debug run --token ${CLOUDFLARED_TOKEN} --url http://proxy:80'
  #   command: 'tunnel --no-autoupdate --loglevel debug run --token ${CLOUDFLARED_TOKEN}'
  #   # ports:
  #   #   - 8080:8080
  #   restart: 'on-failure'
  #   networks:
  #     - proxy-tier
  #   depends_on:
  #     - proxy

volumes:
  joplin_data:

networks:
  proxy-tier:
