version: '3'
services:
  backend:
    build: ./backend
    restart: unless-stopped
    # user: ${UID}:${GUID}
    volumes:
      - ./backend:/usr/local/src/app/backend
      # specify joplin data as a persistent docker volume (defined below)
      - joplin_data:/root/.config/joplin
      # use timezone information from host machine
      # - /etc/timezone:/etc/timezone:ro
      # - /etc/localtime:/etc/localtime:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro 
    env_file:
      - ./backend/.env
    environment:
      - HOSTNAME=${NAME}
      # This ensures that errors are printed as they occur, which
      # makes debugging easier.
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=DEBUG
      - DEV_MODE=1
      # override these variables from the .env file:
      - SPOTIFY_TOKEN_CACHE_PATH=/usr/local/src/app/backend/token_cache/spotify.json
      - GOOGLECALENDAR_TOKEN_CACHE=/usr/local/src/app/backend/token_cache/googlecalendar_token.json
      - GOOGLECALENDAR_CREDENTIALS_FILE=/usr/local/src/app/backend/token_cache/googlecalendar_credentials.json
      - GOOGLEPHOTOS_TOKEN_CACHE=/usr/local/src/app/backend/token_cache/googlephotos_token.json
      - JOPLIN_BASE_URL=http://host.docker.internal:41185
    # command: ["main:app", "--host", "0.0.0.0", "--reload"]
    ports:
      - 41184:41184
    #     - 8888:8888
  mydiary-vuetify:
    build: ./mydiary-vuetify
    # We can't mount the entire UI directory, since JavaScript dependencies
    # (`node_modules`) live at that location.
    restart: unless-stopped
    # user: ${UID}:${GUID}
    volumes:
      - ./mydiary-vuetify/src:/usr/local/src/app/mydiary-vuetify/src
      - ./mydiary-vuetify/public:/usr/local/src/app/mydiary-vuetify/public
      - ./mydiary-vuetify/build:/usr/local/src/app/mydiary-vuetify/build
      - ./mydiary-vuetify/package.json:/usr/local/src/app/mydiary-vuetify/package.json
      - ./mydiary-vuetify/tsconfig.json:/usr/local/src/app/mydiary-vuetify/tsconfig.json
      - ./mydiary-vuetify/tsconfig.node.json:/usr/local/src/app/mydiary-vuetify/tsconfig.node.json
      - ./mydiary-vuetify/.prettierrc:/usr/local/src/app/mydiary-vuetify/.prettierrc
      - ./mydiary-vuetify/package-lock.json:/usr/local/src/app/mydiary-vuetify/package-lock.json
      - ./mydiary-vuetify/vite.config.ts:/usr/local/src/app/mydiary-vuetify/vite.config.ts
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro 
      # use timezone information from host machine
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - NODE_ENV=development
    ports:
        - 3001:3001
  proxy-vue:
    image: nginx:1.25
    restart: unless-stopped
    volumes:
      - ./nginx-vue/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8086:80
    depends_on:
      - backend
      - mydiary-vuetify
    networks:
      - proxy-tier
      - default
  # cloudflared:
  #   image: cloudflare/cloudflared:2023.5.1
  #   # volumes: 
  #   #   - ./cloudflared:/etc/cloudflared
  #   # env_file:
  #   #   - ./cloudflared/cloudflared.env
  #   # command: 'tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN} --hello-world'
  #   # command: 'tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN} --url http://localhost:48916'
  #   # command: 'tunnel --no-autoupdate --loglevel debug run --token ${CLOUDFLARED_TOKEN} --url http://proxy:80'
  #   command: 'tunnel --no-autoupdate --loglevel debug run --token ${CLOUDFLARED_TOKEN}'
  #   # ports:
  #   #   - 8080:8080
  #   restart: 'on-failure'
  #   networks:
  #     - proxy-tier
  #   depends_on:
  #     - proxy

volumes:
  joplin_data:

networks:
  proxy-tier:
