[tool.poetry]
name = "mydiary"
version = "0.1.0"
description = ""
authors = ["h1-the-swan <jason.portenoy@gmail.com>"]
packages = [
	{ include = "mydiary" },
]

[tool.poetry.dependencies]
python = "^3.8"
python-dotenv = "^1.0.0"
pydantic = "^1.10.7"
spotipy = "^2.22.1"
pocket = "^0.3.6"
google-api-python-client = "^2.89.0"
google-auth-httplib2 = "^0.1.0"
google-auth-oauthlib = "^1.0.0"
pendulum = "^2.1.2"
Pillow = "^10.0.0"
sqlmodel = "^0.0.8"
alembic = "^1.11.1"
fastapi = "^0.101.0"
uvicorn = {extras = ["standard"], version = "^0.23.0"}
lxml = "^4.9.0"

[tool.poetry.dev-dependencies]
pytest = "^7.4"
jupyter = "^1.0.0"
black = "^23.1"
humanfriendly = "^10.0"
pandas = "^2.0.3"
SQLAlchemy = "^1.4.27"
psycopg2-binary = "^2.9.2"
pylint = "^2.17.4"
pytest-cov = "^4.1.0"
httpx = "^0.24.1"

[tool.poetry.group.dev.dependencies]
imagehash = "^4.3.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
