[tool.poetry]
name = "mydiary"
version = "0.1.0"
description = ""
authors = ["h1-the-swan <jason.portenoy@gmail.com>"]
packages = [
	{ include = "mydiary" },
]

[tool.poetry.dependencies]
python = "^3.8"
python-dotenv = "^0.21.0"
pydantic = "^1.10.4"
spotipy = "^2.19.0"
pocket = "^0.3.6"
google-api-python-client = "^2.31.0"
google-auth-httplib2 = "^0.1.0"
google-auth-oauthlib = "^0.8.0"
pendulum = "^2.1.2"
Pillow = "^9.4.0"
sqlmodel = "^0.0.8"
alembic = "^1.9.1"
fastapi = "^0.89.0"
uvicorn = {extras = ["standard"], version = "^0.20.0"}
lxml = "^4.9.0"

[tool.poetry.dev-dependencies]
pytest = "^7.2"
jupyter = "^1.0.0"
black = "^23.1a1"
humanfriendly = "^10.0"
pandas = "^1.3.4"
SQLAlchemy = "^1.4.27"
psycopg2-binary = "^2.9.2"
pylint = "^2.12.1"
pytest-cov = "^4.0.0"
httpx = "^0.23.1"

[tool.poetry.group.dev.dependencies]
imagehash = "^4.3.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
