[tool.poetry]
name = "mydiary"
version = "0.1.0"
description = ""
authors = ["h1-the-swan <jason.portenoy@gmail.com>"]
packages = [
	{ include = "mydiary" },
]

[tool.poetry.dependencies]
python = "^3.10"
python-dotenv = "^1.0.0"
pydantic = "^2.5.3"
spotipy = "^2.22.1"
pocket = "^0.3.6"
google-api-python-client = "^2.111.0"
google-auth-httplib2 = "^0.2.0"
google-auth-oauthlib = "^1.0.0"
pendulum = "^3.0.0"
Pillow = "^10.0.0"
sqlmodel = "^0.0.14"
alembic = "^1.13.1"
fastapi = "^0.106"
uvicorn = {extras = ["standard"], version = "^0.24.0"}
lxml = "^4.9.0"

[tool.poetry.dev-dependencies]
humanfriendly = "^10.0"
pytest-cov = "^4.1.0"

[tool.poetry.group.dev.dependencies]
pylint = "^3.0.2"
jupyter = "^1.0.0"
black = "^23.11.0"
pytest = "^7.4.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
