/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * mydiary
 * OpenAPI spec version: 0.1.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export type DogCreateHowMet = string | null;

export type DogCreateWhenMet = string | null;

export type DogCreateOwners = string | null;

export type DogCreateEstimatedBday = string | null;

export type DogCreateNotes = string | null;

export interface DogCreate {
  name: string;
  how_met?: DogCreateHowMet;
  when_met?: DogCreateWhenMet;
  owners?: DogCreateOwners;
  estimated_bday?: DogCreateEstimatedBday;
  notes?: DogCreateNotes;
}

export type DogReadHowMet = string | null;

export type DogReadWhenMet = string | null;

export type DogReadOwners = string | null;

export type DogReadEstimatedBday = string | null;

export type DogReadNotes = string | null;

export interface DogRead {
  name: string;
  how_met?: DogReadHowMet;
  when_met?: DogReadWhenMet;
  owners?: DogReadOwners;
  estimated_bday?: DogReadEstimatedBday;
  notes?: DogReadNotes;
  id: number;
}

export type DogUpdateName = string | null;

export type DogUpdateHowMet = string | null;

export type DogUpdateWhenMet = string | null;

export type DogUpdateOwners = string | null;

export type DogUpdateEstimatedBday = string | null;

export type DogUpdateNotes = string | null;

export interface DogUpdate {
  name?: DogUpdateName;
  how_met?: DogUpdateHowMet;
  when_met?: DogUpdateWhenMet;
  owners?: DogUpdateOwners;
  estimated_bday?: DogUpdateEstimatedBday;
  notes?: DogUpdateNotes;
}

export type GoogleCalendarEventReadLocation = string | null;

export type GoogleCalendarEventReadDescription = string | null;

export type GoogleCalendarEventReadTimeLastApiSync = string | null;

export interface GoogleCalendarEventRead {
  id?: string;
  summary?: string;
  location?: GoogleCalendarEventReadLocation;
  description?: GoogleCalendarEventReadDescription;
  start?: string;
  end?: string;
  start_timezone?: string;
  end_timezone?: string;
  time_last_api_sync?: GoogleCalendarEventReadTimeLastApiSync;
}

export interface GooglePhotosThumbnail {
  baseUrl: string;
  width: number;
  height: number;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export type JoplinNoteBody = string | null;

export type JoplinNoteBodyHash = string | null;

export type JoplinNoteTimeLastApiSync = string | null;

export interface JoplinNote {
  id: string;
  parent_id: string;
  title: string;
  body?: JoplinNoteBody;
  created_time: string;
  updated_time: string;
  body_hash?: JoplinNoteBodyHash;
  has_words?: boolean;
  has_images?: boolean;
  time_last_api_sync?: JoplinNoteTimeLastApiSync;
}

export type MyDiaryImageReadName = string | null;

export type MyDiaryImageReadFilepath = string | null;

export type MyDiaryImageReadNextcloudPath = string | null;

export type MyDiaryImageReadDescription = string | null;

export type MyDiaryImageReadJoplinResourceId = string | null;

export type MyDiaryImageReadOrigImageHash = string | null;

export interface MyDiaryImageRead {
  hash: string;
  name?: MyDiaryImageReadName;
  filepath?: MyDiaryImageReadFilepath;
  nextcloud_path?: MyDiaryImageReadNextcloudPath;
  description?: MyDiaryImageReadDescription;
  thumbnail_size: number;
  joplin_resource_id?: MyDiaryImageReadJoplinResourceId;
  created_at: string;
  orig_image_hash?: MyDiaryImageReadOrigImageHash;
  id: number;
}

export type PerformSongCreateArtistName = string | null;

export type PerformSongCreateSpotifyId = string | null;

export type PerformSongCreateNotes = string | null;

export type PerformSongCreatePerformUrl = string | null;

export type PerformSongCreateCreatedAt = string | null;

export type PerformSongCreateKey = string | null;

export type PerformSongCreateCapo = number | null;

export type PerformSongCreateLyrics = string | null;

export type PerformSongCreateLearnedDt = string | null;

export interface PerformSongCreate {
  name: string;
  artist_name?: PerformSongCreateArtistName;
  learned?: boolean;
  spotify_id?: PerformSongCreateSpotifyId;
  notes?: PerformSongCreateNotes;
  perform_url?: PerformSongCreatePerformUrl;
  created_at?: PerformSongCreateCreatedAt;
  key?: PerformSongCreateKey;
  capo?: PerformSongCreateCapo;
  lyrics?: PerformSongCreateLyrics;
  learned_dt?: PerformSongCreateLearnedDt;
}

export type PerformSongReadArtistName = string | null;

export type PerformSongReadSpotifyId = string | null;

export type PerformSongReadNotes = string | null;

export type PerformSongReadPerformUrl = string | null;

export type PerformSongReadCreatedAt = string | null;

export type PerformSongReadKey = string | null;

export type PerformSongReadCapo = number | null;

export type PerformSongReadLyrics = string | null;

export type PerformSongReadLearnedDt = string | null;

export interface PerformSongRead {
  name: string;
  artist_name?: PerformSongReadArtistName;
  learned?: boolean;
  spotify_id?: PerformSongReadSpotifyId;
  notes?: PerformSongReadNotes;
  perform_url?: PerformSongReadPerformUrl;
  created_at?: PerformSongReadCreatedAt;
  key?: PerformSongReadKey;
  capo?: PerformSongReadCapo;
  lyrics?: PerformSongReadLyrics;
  learned_dt?: PerformSongReadLearnedDt;
  id: number;
}

export type PerformSongUpdateName = string | null;

export type PerformSongUpdateArtistName = string | null;

export type PerformSongUpdateLearned = boolean | null;

export type PerformSongUpdateSpotifyId = string | null;

export type PerformSongUpdateNotes = string | null;

export type PerformSongUpdatePerformUrl = string | null;

export type PerformSongUpdateCreatedAt = string | null;

export type PerformSongUpdateKey = string | null;

export type PerformSongUpdateCapo = number | null;

export type PerformSongUpdateLyrics = string | null;

export type PerformSongUpdateLearnedDt = string | null;

export interface PerformSongUpdate {
  name?: PerformSongUpdateName;
  artist_name?: PerformSongUpdateArtistName;
  learned?: PerformSongUpdateLearned;
  spotify_id?: PerformSongUpdateSpotifyId;
  notes?: PerformSongUpdateNotes;
  perform_url?: PerformSongUpdatePerformUrl;
  created_at?: PerformSongUpdateCreatedAt;
  key?: PerformSongUpdateKey;
  capo?: PerformSongUpdateCapo;
  lyrics?: PerformSongUpdateLyrics;
  learned_dt?: PerformSongUpdateLearnedDt;
}

export type PocketArticleReadTimeAdded = string | null;

export type PocketArticleReadTimeUpdated = string | null;

export type PocketArticleReadTimeRead = string | null;

export type PocketArticleReadTimeFavorited = string | null;

export type PocketArticleReadListenDurationEstimate = number | null;

export type PocketArticleReadWordCount = number | null;

export type PocketArticleReadTopImageUrl = string | null;

export type PocketArticleReadRaindropId = number | null;

export type PocketArticleReadTimePocketRaindropSync = string | null;

export type PocketArticleReadTimeLastApiSync = string | null;

export interface PocketArticleRead {
  given_title: string;
  resolved_title: string;
  url: string;
  favorite: boolean;
  status: PocketStatusEnum;
  time_added?: PocketArticleReadTimeAdded;
  time_updated?: PocketArticleReadTimeUpdated;
  time_read?: PocketArticleReadTimeRead;
  time_favorited?: PocketArticleReadTimeFavorited;
  listen_duration_estimate?: PocketArticleReadListenDurationEstimate;
  word_count?: PocketArticleReadWordCount;
  top_image_url?: PocketArticleReadTopImageUrl;
  raindrop_id?: PocketArticleReadRaindropId;
  time_pocket_raindrop_sync?: PocketArticleReadTimePocketRaindropSync;
  time_last_api_sync?: PocketArticleReadTimeLastApiSync;
  tags?: TagRead[];
}

export type PocketArticleUpdateGivenTitle = string | null;

export type PocketArticleUpdateResolvedTitle = string | null;

export type PocketArticleUpdateUrl = string | null;

export type PocketArticleUpdateFavorite = boolean | null;

export type PocketArticleUpdateStatus = PocketStatusEnum | null;

export type PocketArticleUpdateTimeAdded = string | null;

export type PocketArticleUpdateTimeUpdated = string | null;

export type PocketArticleUpdateTimeRead = string | null;

export type PocketArticleUpdateTimeFavorited = string | null;

export type PocketArticleUpdateListenDurationEstimate = number | null;

export type PocketArticleUpdateWordCount = number | null;

export type PocketArticleUpdateTopImageUrl = string | null;

export type PocketArticleUpdatePocketTags = string[] | null;

export type PocketArticleUpdateRaindropId = number | null;

export type PocketArticleUpdateTimePocketRaindropSync = string | null;

export type PocketArticleUpdateTimeLastApiSync = string | null;

export interface PocketArticleUpdate {
  given_title?: PocketArticleUpdateGivenTitle;
  resolved_title?: PocketArticleUpdateResolvedTitle;
  url?: PocketArticleUpdateUrl;
  favorite?: PocketArticleUpdateFavorite;
  status?: PocketArticleUpdateStatus;
  time_added?: PocketArticleUpdateTimeAdded;
  time_updated?: PocketArticleUpdateTimeUpdated;
  time_read?: PocketArticleUpdateTimeRead;
  time_favorited?: PocketArticleUpdateTimeFavorited;
  listen_duration_estimate?: PocketArticleUpdateListenDurationEstimate;
  word_count?: PocketArticleUpdateWordCount;
  top_image_url?: PocketArticleUpdateTopImageUrl;
  pocket_tags?: PocketArticleUpdatePocketTags;
  raindrop_id?: PocketArticleUpdateRaindropId;
  time_pocket_raindrop_sync?: PocketArticleUpdateTimePocketRaindropSync;
  time_last_api_sync?: PocketArticleUpdateTimeLastApiSync;
}

export type PocketStatusEnum = typeof PocketStatusEnum[keyof typeof PocketStatusEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PocketStatusEnum = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
} as const;

export type RecipeCreateNotes = string | null;

export interface RecipeCreate {
  name: string;
  upvotes?: number;
  notes?: RecipeCreateNotes;
}

export type RecipeReadNotes = string | null;

export interface RecipeRead {
  name: string;
  upvotes?: number;
  notes?: RecipeReadNotes;
  id: number;
}

export interface SpotifyTrackBase {
  spotify_id: string;
  name: string;
  artist_name: string;
  uri: string;
}

export type SpotifyTrackHistoryReadId = number | null;

export type SpotifyTrackHistoryReadContextUri = string | null;

export type SpotifyTrackHistoryReadContextName = string | null;

export type SpotifyTrackHistoryReadContextType = number | null;

export interface SpotifyTrackHistoryRead {
  id?: SpotifyTrackHistoryReadId;
  played_at: string;
  context_uri?: SpotifyTrackHistoryReadContextUri;
  context_name?: SpotifyTrackHistoryReadContextName;
  context_type?: SpotifyTrackHistoryReadContextType;
  spotify_id: string;
  id_: number;
  track: SpotifyTrackBase;
}

export type TagReadNumPocketArticles = number | null;

export interface TagRead {
  name: string;
  is_pocket_tag?: boolean;
  num_pocket_articles?: TagReadNumPocketArticles;
}

export interface TimeZoneChange {
  changed_at: string;
  tz_before: string;
  tz_after: string;
}

export type ValidationErrorLocItem = string | number;

export interface ValidationError {
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
}

export type DbStatusParams = {
more?: boolean;
};

export type DbStatus200 = { [key: string]: unknown };

export type RefreshGCalTokenParams = {
code: string;
};

export type ReadGCalEventsParams = {
offset?: number;
limit?: number;
};

export type ReadTagsParams = {
offset?: number;
limit?: number;
is_pocket_tag?: boolean | null;
};

export type ReadPocketArticlesParams = {
offset?: number;
limit?: number;
status?: number[] | null;
/**
 * Tag names (comma separated
 */
tags?: string | null;
dateMin?: string | null;
dateMax?: string | null;
/**
 * Year added (ignored if dateRange is specified)
 */
year?: number | null;
};

export type ReadSpotifyHistoryParams = {
offset?: number;
limit?: number;
};

export type JoplinInitNoteParams = {
tz?: string;
body?: string | null;
};

export type DayInitMarkdownParams = {
tz?: string;
};

export type JoplinGetNoteParams = {
remove_image_refs?: boolean;
};

export type JoplinUpdateNoteParams = {
tz?: string;
};

export type JoplinGetInfoAllDaysParams = {
min_dt: string;
max_dt: string;
};

export type GetNextcloudImageNextcloudThumbnailImgGetParams = {
url: string;
};

export type NextcloudPhotosAddToJoplin200 = { [key: string]: unknown };

export type ReadPerformSongsListParams = {
offset?: number;
limit?: number;
};

export type ReadDogsListParams = {
offset?: number;
limit?: number;
};

export type ReadRecipesListParams = {
offset?: number;
limit?: number;
};

export type ReadTimeZoneChangeListParams = {
offset?: number;
limit?: number;
};

export type CreateTimeZoneChangeParams = {
dt: string;
tz_before: string;
tz_after: string;
};

export type ExperimentalGetSpotifyPlaylistExperimentalGetSpotifyPlaylistGetParams = {
playlist_id: string;
};

export type ExperimentalGetSpotifyAudioFeaturesExperimentalGetSpotifyAudioFeaturesGetParams = {
track_id: string;
};

/**
 * @summary Testhealthcheck
 */
export const testHealthCheck2 = <TData = AxiosResponse<unknown>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/testhealthcheck`,options
    );
  }

/**
 * @summary Db Status
 */
export const dbStatus = <TData = AxiosResponse<DbStatus200>>(
    params?: DbStatusParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/db_status`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Get Gcal Auth Url
 */
export const getGCalAuthUrl = <TData = AxiosResponse<string>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/gcal/get_auth_url`,{
        responseType: 'text',
    ...options,}
    );
  }

/**
 * @summary Refresh Gcal Token
 */
export const refreshGCalToken = <TData = AxiosResponse<unknown>>(
    params: RefreshGCalTokenParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/gcal/refresh_token`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Check Gcal Auth
 */
export const checkGCalAuth = <TData = AxiosResponse<unknown>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/gcal/check_auth`,undefined,options
    );
  }

/**
 * @summary Read Gcal Events
 */
export const readGCalEvents = <TData = AxiosResponse<GoogleCalendarEventRead[]>>(
    params?: ReadGCalEventsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/gcal/events`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Read Tags
 */
export const readTags = <TData = AxiosResponse<TagRead[]>>(
    params?: ReadTagsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/tags`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Count Pocket Articles
 */
export const countPocketArticles = <TData = AxiosResponse<number>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/pocket/articles/count`,options
    );
  }

/**
 * @summary Read Pocket Articles
 */
export const readPocketArticles = <TData = AxiosResponse<PocketArticleRead[]>>(
    params?: ReadPocketArticlesParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/pocket/articles`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Update Pocket Article
 */
export const updatePocketArticle = <TData = AxiosResponse<PocketArticleRead>>(
    articleId: number,
    pocketArticleUpdate: PocketArticleUpdate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/pocket/articles/${articleId}`,
      pocketArticleUpdate,options
    );
  }

/**
 * @summary Read Spotify History
 */
export const readSpotifyHistory = <TData = AxiosResponse<SpotifyTrackHistoryRead[]>>(
    params?: ReadSpotifyHistoryParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/spotify/history`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Spotify History Count
 */
export const spotifyHistoryCount = <TData = AxiosResponse<number>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/spotify/history/count`,options
    );
  }

/**
 * @summary Get Spotify Image Url
 */
export const getSpotifyImageUrl = <TData = AxiosResponse<string>>(
    trackId: string | null, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/spotify/album_image_url/${trackId}`,{
        responseType: 'text',
    ...options,}
    );
  }

/**
 * @summary Spotify Save Recent Tracks To Database
 */
export const spotifySaveRecentTracksToDatabase = <TData = AxiosResponse<number>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/spotify/save_recent_tracks_to_database`,undefined,options
    );
  }

/**
 * @summary Joplin Get Note Id
 */
export const joplinGetNoteId = <TData = AxiosResponse<string>>(
    dt: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/joplin/get_note_id/${dt}`,{
        responseType: 'text',
    ...options,}
    );
  }

/**
 * @summary Joplin Init Note
 */
export const joplinInitNote = <TData = AxiosResponse<string>>(
    dt: string,
    params?: JoplinInitNoteParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/joplin/init_note/${dt}`,undefined,{
        responseType: 'text',
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Day Init Markdown
 */
export const dayInitMarkdown = <TData = AxiosResponse<unknown>>(
    dt: string,
    params?: DayInitMarkdownParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/day_init_markdown/${dt}`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Joplin Get Note
 */
export const joplinGetNote = <TData = AxiosResponse<JoplinNote>>(
    noteId: string,
    params?: JoplinGetNoteParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/joplin/get_note/${noteId}`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Joplin Get Note Images
 */
export const joplinNoteImages = <TData = AxiosResponse<MyDiaryImageRead[]>>(
    noteId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/joplin/get_note_images/${noteId}`,options
    );
  }

/**
 * @summary Joplin Update Note
 */
export const joplinUpdateNote = <TData = AxiosResponse<unknown>>(
    dt: string,
    params?: JoplinUpdateNoteParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/joplin/update_note/${dt}`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Joplin Get Info All Days
 */
export const joplinGetInfoAllDays = <TData = AxiosResponse<unknown[]>>(
    params: JoplinGetInfoAllDaysParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/joplin/get_info_all_days`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Google Photos Thumbnails Url
 */
export const googlePhotosThumbnailUrls = <TData = AxiosResponse<GooglePhotosThumbnail[]>>(
    dt: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/googlephotos/thumbnails/${dt}`,options
    );
  }

/**
 * @summary Google Photos Add To Joplin
 */
export const googlePhotosAddToJoplin = <TData = AxiosResponse<unknown>>(
    noteId: string,
    googlePhotosThumbnail: GooglePhotosThumbnail[], options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/googlephotos/add_to_joplin/${noteId}`,
      googlePhotosThumbnail,options
    );
  }

/**
 * @summary Nextcloud Photos Thumbnails Url
 */
export const nextcloudPhotosThumbnailUrls = <TData = AxiosResponse<string[]>>(
    dt: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/nextcloud/thumbnails/${dt}`,options
    );
  }

/**
 * @summary Get Nextcloud Image
 */
export const getNextcloudImageNextcloudThumbnailImgGet = <TData = AxiosResponse<unknown>>(
    params: GetNextcloudImageNextcloudThumbnailImgGetParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/nextcloud/thumbnail_img`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Nextcloud Photos Add To Joplin
 */
export const nextcloudPhotosAddToJoplin = <TData = AxiosResponse<NextcloudPhotosAddToJoplin200>>(
    noteId: string,
    nextcloudPhotosAddToJoplinBody: string[], options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/nextcloud/add_to_joplin/${noteId}`,
      nextcloudPhotosAddToJoplinBody,options
    );
  }

/**
 * @summary Create Perform Song
 */
export const createPerformSong = <TData = AxiosResponse<PerformSongRead>>(
    performSongCreate: PerformSongCreate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/performsongs/`,
      performSongCreate,options
    );
  }

/**
 * @summary Read Perform Songs
 */
export const readPerformSongsList = <TData = AxiosResponse<PerformSongRead[]>>(
    params?: ReadPerformSongsListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/performsongs/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Perform Song  Count
 */
export const performSongCount = <TData = AxiosResponse<number>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/performsongs/count`,options
    );
  }

/**
 * @summary Read Perform Song
 */
export const readPerformSong = <TData = AxiosResponse<PerformSongRead>>(
    performSongId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/performsongs/${performSongId}`,options
    );
  }

/**
 * @summary Update Perform Song
 */
export const updatePerformSong = <TData = AxiosResponse<PerformSongRead>>(
    performSongId: number,
    performSongUpdate: PerformSongUpdate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/performsongs/${performSongId}`,
      performSongUpdate,options
    );
  }

/**
 * @summary Delete Perform Song
 */
export const deletePerformSong = <TData = AxiosResponse<unknown>>(
    performSongId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/performsongs/${performSongId}`,options
    );
  }

/**
 * @summary Create Dog
 */
export const createDog = <TData = AxiosResponse<DogRead>>(
    dogCreate: DogCreate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/dogs/`,
      dogCreate,options
    );
  }

/**
 * @summary Read Dogs
 */
export const readDogsList = <TData = AxiosResponse<DogRead[]>>(
    params?: ReadDogsListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/dogs/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Read Dog
 */
export const readDog = <TData = AxiosResponse<DogRead>>(
    dogId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/dogs/${dogId}`,options
    );
  }

/**
 * @summary Update Dog
 */
export const updateDog = <TData = AxiosResponse<DogRead>>(
    dogId: number,
    dogUpdate: DogUpdate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/dogs/${dogId}`,
      dogUpdate,options
    );
  }

/**
 * @summary Delete Dog
 */
export const deleteDog = <TData = AxiosResponse<unknown>>(
    dogId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/dogs/${dogId}`,options
    );
  }

/**
 * @summary Create Recipe
 */
export const createRecipe = <TData = AxiosResponse<RecipeRead>>(
    recipeCreate: RecipeCreate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/recipes/`,
      recipeCreate,options
    );
  }

/**
 * @summary Read Recipes
 */
export const readRecipesList = <TData = AxiosResponse<RecipeRead>>(
    params?: ReadRecipesListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/recipes/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Read Timezonechange
 */
export const readTimeZoneChangeList = <TData = AxiosResponse<TimeZoneChange[]>>(
    params?: ReadTimeZoneChangeListParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/tzchange/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Create Timezonechange
 */
export const createTimeZoneChange = <TData = AxiosResponse<TimeZoneChange>>(
    params: CreateTimeZoneChangeParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/tzchange/`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Send Api Json
 */
export const sendApiJsonGenerateOpenapiJsonGet = <TData = AxiosResponse<unknown>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/generate_openapi_json`,options
    );
  }

/**
 * @summary Experimental Get Spotify Playlist
 */
export const experimentalGetSpotifyPlaylistExperimentalGetSpotifyPlaylistGet = <TData = AxiosResponse<unknown>>(
    params: ExperimentalGetSpotifyPlaylistExperimentalGetSpotifyPlaylistGetParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/experimental/get_spotify_playlist`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Experimental Get Spotify Audio Features
 */
export const experimentalGetSpotifyAudioFeaturesExperimentalGetSpotifyAudioFeaturesGet = <TData = AxiosResponse<unknown>>(
    params: ExperimentalGetSpotifyAudioFeaturesExperimentalGetSpotifyAudioFeaturesGetParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/experimental/get_spotify_audio_features`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Experimental Lifespan
 */
export const experimentalLifespanExperimentalLifespanGet = <TData = AxiosResponse<unknown>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/experimental/lifespan`,options
    );
  }

/**
 * @summary Joplinevents
 */
export const joplineventsExperimentalJoplineventsGet = <TData = AxiosResponse<unknown>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/experimental/joplinevents`,options
    );
  }

export type TestHealthCheck2Result = AxiosResponse<unknown>
export type DbStatusResult = AxiosResponse<DbStatus200>
export type GetGCalAuthUrlResult = AxiosResponse<string>
export type RefreshGCalTokenResult = AxiosResponse<unknown>
export type CheckGCalAuthResult = AxiosResponse<unknown>
export type ReadGCalEventsResult = AxiosResponse<GoogleCalendarEventRead[]>
export type ReadTagsResult = AxiosResponse<TagRead[]>
export type CountPocketArticlesResult = AxiosResponse<number>
export type ReadPocketArticlesResult = AxiosResponse<PocketArticleRead[]>
export type UpdatePocketArticleResult = AxiosResponse<PocketArticleRead>
export type ReadSpotifyHistoryResult = AxiosResponse<SpotifyTrackHistoryRead[]>
export type SpotifyHistoryCountResult = AxiosResponse<number>
export type GetSpotifyImageUrlResult = AxiosResponse<string>
export type SpotifySaveRecentTracksToDatabaseResult = AxiosResponse<number>
export type JoplinGetNoteIdResult = AxiosResponse<string>
export type JoplinInitNoteResult = AxiosResponse<string>
export type DayInitMarkdownResult = AxiosResponse<unknown>
export type JoplinGetNoteResult = AxiosResponse<JoplinNote>
export type JoplinNoteImagesResult = AxiosResponse<MyDiaryImageRead[]>
export type JoplinUpdateNoteResult = AxiosResponse<unknown>
export type JoplinGetInfoAllDaysResult = AxiosResponse<unknown[]>
export type GooglePhotosThumbnailUrlsResult = AxiosResponse<GooglePhotosThumbnail[]>
export type GooglePhotosAddToJoplinResult = AxiosResponse<unknown>
export type NextcloudPhotosThumbnailUrlsResult = AxiosResponse<string[]>
export type GetNextcloudImageNextcloudThumbnailImgGetResult = AxiosResponse<unknown>
export type NextcloudPhotosAddToJoplinResult = AxiosResponse<NextcloudPhotosAddToJoplin200>
export type CreatePerformSongResult = AxiosResponse<PerformSongRead>
export type ReadPerformSongsListResult = AxiosResponse<PerformSongRead[]>
export type PerformSongCountResult = AxiosResponse<number>
export type ReadPerformSongResult = AxiosResponse<PerformSongRead>
export type UpdatePerformSongResult = AxiosResponse<PerformSongRead>
export type DeletePerformSongResult = AxiosResponse<unknown>
export type CreateDogResult = AxiosResponse<DogRead>
export type ReadDogsListResult = AxiosResponse<DogRead[]>
export type ReadDogResult = AxiosResponse<DogRead>
export type UpdateDogResult = AxiosResponse<DogRead>
export type DeleteDogResult = AxiosResponse<unknown>
export type CreateRecipeResult = AxiosResponse<RecipeRead>
export type ReadRecipesListResult = AxiosResponse<RecipeRead>
export type ReadTimeZoneChangeListResult = AxiosResponse<TimeZoneChange[]>
export type CreateTimeZoneChangeResult = AxiosResponse<TimeZoneChange>
export type SendApiJsonGenerateOpenapiJsonGetResult = AxiosResponse<unknown>
export type ExperimentalGetSpotifyPlaylistExperimentalGetSpotifyPlaylistGetResult = AxiosResponse<unknown>
export type ExperimentalGetSpotifyAudioFeaturesExperimentalGetSpotifyAudioFeaturesGetResult = AxiosResponse<unknown>
export type ExperimentalLifespanExperimentalLifespanGetResult = AxiosResponse<unknown>
export type JoplineventsExperimentalJoplineventsGetResult = AxiosResponse<unknown>
