"""add pocketarticle and tag tables

Revision ID: 07f0c7762017
Revises: 8e6797e97472
Create Date: 2022-02-05 17:34:34.289011

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '07f0c7762017'
down_revision = '8e6797e97472'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pocketarticle',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('given_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resolved_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('favorite', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('time_added', sa.DateTime(), nullable=True),
    sa.Column('time_updated', sa.DateTime(), nullable=True),
    sa.Column('time_read', sa.DateTime(), nullable=True),
    sa.Column('time_favorited', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag',
    sa.Column('uid', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pocket_tag_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tag_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_tag_pocket_tag_id'), ['pocket_tag_id'], unique=False)

    op.create_table('pocketarticletaglink',
    sa.Column('article_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tag_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['pocketarticle.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.pocket_tag_id'], ),
    sa.PrimaryKeyConstraint('article_id', 'tag_id')
    )
    with op.batch_alter_table('googlecalendarevent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_test_col', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('googlecalendarevent', schema=None) as batch_op:
        batch_op.drop_column('new_test_col')

    op.drop_table('pocketarticletaglink')
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tag_pocket_tag_id'))
        batch_op.drop_index(batch_op.f('ix_tag_name'))

    op.drop_table('tag')
    op.drop_table('pocketarticle')
    # ### end Alembic commands ###
