"""new columns in pocketarticle table

Revision ID: 0c87b03768d7
Revises: c50f8b629136
Create Date: 2022-02-05 17:49:07.385145

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '0c87b03768d7'
down_revision = 'c50f8b629136'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pocketarticle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('listen_duration_estimate', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('word_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('excerpt', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.create_index(batch_op.f('ix_pocketarticle_favorite'), ['favorite'], unique=False)
        batch_op.create_index(batch_op.f('ix_pocketarticle_given_title'), ['given_title'], unique=False)
        batch_op.create_index(batch_op.f('ix_pocketarticle_listen_duration_estimate'), ['listen_duration_estimate'], unique=False)
        batch_op.create_index(batch_op.f('ix_pocketarticle_resolved_title'), ['resolved_title'], unique=False)
        batch_op.create_index(batch_op.f('ix_pocketarticle_time_added'), ['time_added'], unique=False)
        batch_op.create_index(batch_op.f('ix_pocketarticle_time_favorited'), ['time_favorited'], unique=False)
        batch_op.create_index(batch_op.f('ix_pocketarticle_time_read'), ['time_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_pocketarticle_time_updated'), ['time_updated'], unique=False)
        batch_op.create_index(batch_op.f('ix_pocketarticle_word_count'), ['word_count'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pocketarticle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pocketarticle_word_count'))
        batch_op.drop_index(batch_op.f('ix_pocketarticle_time_updated'))
        batch_op.drop_index(batch_op.f('ix_pocketarticle_time_read'))
        batch_op.drop_index(batch_op.f('ix_pocketarticle_time_favorited'))
        batch_op.drop_index(batch_op.f('ix_pocketarticle_time_added'))
        batch_op.drop_index(batch_op.f('ix_pocketarticle_resolved_title'))
        batch_op.drop_index(batch_op.f('ix_pocketarticle_listen_duration_estimate'))
        batch_op.drop_index(batch_op.f('ix_pocketarticle_given_title'))
        batch_op.drop_index(batch_op.f('ix_pocketarticle_favorite'))
        batch_op.drop_column('excerpt')
        batch_op.drop_column('word_count')
        batch_op.drop_column('listen_duration_estimate')

    # ### end Alembic commands ###
