"""add field to Tag

Revision ID: 4e69b49f6a0d
Revises: 49d6c77baef5
Create Date: 2022-02-06 20:14:24.164682

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '4e69b49f6a0d'
down_revision = '49d6c77baef5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_pocket_tag', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_column('is_pocket_tag')

    # ### end Alembic commands ###
