"""remove test col

Revision ID: c50f8b629136
Revises: 07f0c7762017
Create Date: 2022-02-05 17:36:06.235963

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'c50f8b629136'
down_revision = '07f0c7762017'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('googlecalendarevent', schema=None) as batch_op:
        batch_op.drop_column('new_test_col')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('googlecalendarevent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_test_col', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
