"""minor tweaks

Revision ID: 0e296ec9b060
Revises: e943e3d13add
Create Date: 2024-05-04 20:52:10.203087

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '0e296ec9b060'
down_revision = 'e943e3d13add'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pocketarticle', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.INTEGER(),
               type_=sa.Enum('UNREAD', 'ARCHIVED', 'SHOULD_BE_DELETED', name='pocketstatusenum'),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_pocketarticle_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pocketarticle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pocketarticle_status'))
        batch_op.alter_column('status',
               existing_type=sa.Enum('UNREAD', 'ARCHIVED', 'SHOULD_BE_DELETED', name='pocketstatusenum'),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
