"""add status to googlecalendarevent

Revision ID: 17476b75cf80
Revises: 9ecbdf140eb4
Create Date: 2026-10-03 16:01:12.938599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '17476b75cf80'
down_revision: Union[str, None] = '9ecbdf140eb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('googlecalendarevent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), server_default='confirmed', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('googlecalendarevent', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
