"""add timezonechange table

Revision ID: 1d0994fb3e88
Revises: 161692a924d8
Create Date: 2024-09-22 18:45:52.954205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1d0994fb3e88'
down_revision: Union[str, None] = '161692a924d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timezonechange',
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('tz_before', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tz_after', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('changed_at')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timezonechange')
    # ### end Alembic commands ###
