"""add words table

Revision ID: 1d2fdcc3b6dc
Revises: fe286885f86e
Create Date: 2024-12-26 15:42:55.527407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '1d2fdcc3b6dc'
down_revision: Union[str, None] = 'fe286885f86e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mydiarywords',
    sa.Column('joplin_note_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('joplin_note_title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('txt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mydiarywords_created_at'), 'mydiarywords', ['created_at'], unique=False)
    op.create_index(op.f('ix_mydiarywords_hash'), 'mydiarywords', ['hash'], unique=False)
    op.create_index(op.f('ix_mydiarywords_joplin_note_id'), 'mydiarywords', ['joplin_note_id'], unique=False)
    op.create_index(op.f('ix_mydiarywords_joplin_note_title'), 'mydiarywords', ['joplin_note_title'], unique=False)
    op.create_index(op.f('ix_mydiarywords_updated_at'), 'mydiarywords', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mydiarywords_updated_at'), table_name='mydiarywords')
    op.drop_index(op.f('ix_mydiarywords_joplin_note_title'), table_name='mydiarywords')
    op.drop_index(op.f('ix_mydiarywords_joplin_note_id'), table_name='mydiarywords')
    op.drop_index(op.f('ix_mydiarywords_hash'), table_name='mydiarywords')
    op.drop_index(op.f('ix_mydiarywords_created_at'), table_name='mydiarywords')
    op.drop_table('mydiarywords')
    # ### end Alembic commands ###
