"""add updated_at column to audio features table

Revision ID: 4bb955072777
Revises: 7711952fa8b6
Create Date: 2025-02-25 15:24:43.200186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '4bb955072777'
down_revision: Union[str, None] = '7711952fa8b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spotifytrackhistoryaudiofeatures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.create_index(batch_op.f('ix_spotifytrackhistoryaudiofeatures_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spotifytrackhistoryaudiofeatures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spotifytrackhistoryaudiofeatures_updated_at'))
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
