"""add diary_date to mydiaryimage

Revision ID: 4f09dd377b15
Revises: aea3d98b34a7
Create Date: 2026-07-19 22:59:02.965099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '4f09dd377b15'
down_revision: Union[str, None] = 'aea3d98b34a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mydiaryimage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diary_date', sa.Date(), nullable=True))
        batch_op.create_index(batch_op.f('ix_mydiaryimage_diary_date'), ['diary_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mydiaryimage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mydiaryimage_diary_date'))
        batch_op.drop_column('diary_date')

    # ### end Alembic commands ###
