"""add original image hash field to mydiaryimage

Revision ID: 54bc67175129
Revises: 16e8adf5ddb8
Create Date: 2025-01-22 23:44:37.162834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '54bc67175129'
down_revision: Union[str, None] = '16e8adf5ddb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mydiaryimage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orig_image_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.create_index(batch_op.f('ix_mydiaryimage_orig_image_hash'), ['orig_image_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mydiaryimage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mydiaryimage_orig_image_hash'))
        batch_op.drop_column('orig_image_hash')

    # ### end Alembic commands ###
