"""add performsong table

Revision ID: 5bb601663558
Revises: abae23bcb70a
Create Date: 2022-07-03 12:47:36.851386

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '5bb601663558'
down_revision = 'abae23bcb70a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performsong',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('artist_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('learned', sa.Boolean(), nullable=False),
    sa.Column('spotify_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('perform_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['spotify_id'], ['spotifytrack.spotify_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('performsong', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_performsong_artist_name'), ['artist_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_performsong_learned'), ['learned'], unique=False)
        batch_op.create_index(batch_op.f('ix_performsong_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_performsong_spotify_id'), ['spotify_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performsong', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_performsong_spotify_id'))
        batch_op.drop_index(batch_op.f('ix_performsong_name'))
        batch_op.drop_index(batch_op.f('ix_performsong_learned'))
        batch_op.drop_index(batch_op.f('ix_performsong_artist_name'))

    op.drop_table('performsong')
    # ### end Alembic commands ###
