"""add song arrangements and practice runs

Revision ID: 64fa81d8c2b8
Revises: 0652a2a11ff2
Create Date: 2026-09-19 18:05:49.304572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '64fa81d8c2b8'
down_revision: Union[str, None] = '0652a2a11ff2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sectionleveloverride',
    sa.Column('perform_song_id', sa.Integer(), nullable=False),
    sa.Column('section_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('set_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['perform_song_id'], ['performsong.id'], ),
    sa.PrimaryKeyConstraint('perform_song_id', 'section_key')
    )
    op.create_table('songarrangement',
    sa.Column('perform_song_id', sa.Integer(), nullable=False),
    sa.Column('instrument', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('capo', sa.Integer(), nullable=True),
    sa.Column('sheet', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['perform_song_id'], ['performsong.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('perform_song_id', 'instrument', name='uix_songarrangement_song_instrument')
    )
    with op.batch_alter_table('songarrangement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_songarrangement_instrument'), ['instrument'], unique=False)
        batch_op.create_index(batch_op.f('ix_songarrangement_perform_song_id'), ['perform_song_id'], unique=False)

    op.create_table('practicerun',
    sa.Column('perform_song_id', sa.Integer(), nullable=False),
    sa.Column('arrangement_id', sa.Integer(), nullable=True),
    sa.Column('instrument', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('practiced_at', sa.DateTime(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['arrangement_id'], ['songarrangement.id'], ),
    sa.ForeignKeyConstraint(['perform_song_id'], ['performsong.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('practicerun', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_practicerun_arrangement_id'), ['arrangement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_practicerun_perform_song_id'), ['perform_song_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_practicerun_practiced_at'), ['practiced_at'], unique=False)

    op.create_table('practicerunsection',
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('section_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stumbled', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['practicerun.id'], ),
    sa.PrimaryKeyConstraint('run_id', 'section_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('practicerunsection')
    with op.batch_alter_table('practicerun', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_practicerun_practiced_at'))
        batch_op.drop_index(batch_op.f('ix_practicerun_perform_song_id'))
        batch_op.drop_index(batch_op.f('ix_practicerun_arrangement_id'))

    op.drop_table('practicerun')
    with op.batch_alter_table('songarrangement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_songarrangement_perform_song_id'))
        batch_op.drop_index(batch_op.f('ix_songarrangement_instrument'))

    op.drop_table('songarrangement')
    op.drop_table('sectionleveloverride')
    # ### end Alembic commands ###
