"""add created_at column to performsongs table

Revision ID: 72c1841ec029
Revises: 5bb601663558
Create Date: 2022-07-04 18:38:06.756184

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '72c1841ec029'
down_revision = '5bb601663558'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performsong', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_performsong_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performsong', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_performsong_created_at'))
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
