"""add lyrics field to PerformSong

Revision ID: 76195e4bb3e1
Revises: 43f9baca4115
Create Date: 2022-09-30 13:45:19.649949

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '76195e4bb3e1'
down_revision = '43f9baca4115'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performsong', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lyrics', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performsong', schema=None) as batch_op:
        batch_op.drop_column('lyrics')

    # ### end Alembic commands ###
