"""changes to spotify tables

Revision ID: 7b7e1a7b6a0e
Revises: ff8fd8da6b6a
Create Date: 2022-04-17 17:05:46.347634

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '7b7e1a7b6a0e'
down_revision = 'ff8fd8da6b6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spotifycontext', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spotifycontext_context_uri'), ['context_uri'], unique=False)
        batch_op.create_index(batch_op.f('ix_spotifycontext_name'), ['name'], unique=False)

    with op.batch_alter_table('spotifytrack', schema=None) as batch_op:
        batch_op.drop_index('ix_spotifytrack_played_at')
        batch_op.drop_column('played_at')
        batch_op.drop_column('context_uri')
        batch_op.drop_column('context_type')

    with op.batch_alter_table('spotifytrackhistory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('context_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.create_index(batch_op.f('ix_spotifytrackhistory_context_uri'), ['context_uri'], unique=False)
        batch_op.create_index(batch_op.f('ix_spotifytrackhistory_played_at'), ['played_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_spotifytrackhistory_spotify_id'), ['spotify_id'], unique=False)
        batch_op.create_foreign_key(None, 'spotifycontext', ['context_uri'], ['uri'])
        batch_op.create_foreign_key(None, 'spotifytrack', ['spotify_id'], ['spotify_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spotifytrackhistory', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_spotifytrackhistory_spotify_id'))
        batch_op.drop_index(batch_op.f('ix_spotifytrackhistory_played_at'))
        batch_op.drop_index(batch_op.f('ix_spotifytrackhistory_context_uri'))
        batch_op.drop_column('context_uri')

    with op.batch_alter_table('spotifytrack', schema=None) as batch_op:
        batch_op.add_column(sa.Column('context_type', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('context_uri', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('played_at', sa.DATETIME(), nullable=True))
        batch_op.create_index('ix_spotifytrack_played_at', ['played_at'], unique=False)

    with op.batch_alter_table('spotifycontext', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spotifycontext_name'))
        batch_op.drop_index(batch_op.f('ix_spotifycontext_context_uri'))

    # ### end Alembic commands ###
