"""change words column name for title

Revision ID: a2ba3ac2978e
Revises: 041dd88e85f4
Create Date: 2024-12-30 13:12:08.907690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'a2ba3ac2978e'
down_revision: Union[str, None] = '041dd88e85f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mydiarywords', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note_title', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.drop_index('ix_mydiarywords_joplin_note_title')
        batch_op.create_index(batch_op.f('ix_mydiarywords_note_title'), ['note_title'], unique=False)
        batch_op.drop_column('joplin_note_title')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mydiarywords', schema=None) as batch_op:
        batch_op.add_column(sa.Column('joplin_note_title', sa.VARCHAR(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_mydiarywords_note_title'))
        batch_op.create_index('ix_mydiarywords_joplin_note_title', ['joplin_note_title'], unique=False)
        batch_op.drop_column('note_title')

    # ### end Alembic commands ###
