"""rename audio features table

Revision ID: aea3d98b34a7
Revises: 4bb955072777
Create Date: 2025-02-25 15:32:36.953075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'aea3d98b34a7'
down_revision: Union[str, None] = '4bb955072777'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spotifytrackaudiofeatures',
    sa.Column('spotify_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('acousticness', sa.Float(), nullable=False),
    sa.Column('danceability', sa.Float(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('energy', sa.Float(), nullable=False),
    sa.Column('instrumentalness', sa.Float(), nullable=False),
    sa.Column('key', sa.Integer(), nullable=False),
    sa.Column('liveness', sa.Float(), nullable=False),
    sa.Column('mode', sa.Integer(), nullable=False),
    sa.Column('speechiness', sa.Float(), nullable=False),
    sa.Column('tempo', sa.Float(), nullable=False),
    sa.Column('time_signature', sa.Integer(), nullable=False),
    sa.Column('valence', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['spotify_id'], ['spotifytrack.spotify_id'], ),
    sa.PrimaryKeyConstraint('spotify_id')
    )
    with op.batch_alter_table('spotifytrackaudiofeatures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spotifytrackaudiofeatures_acousticness'), ['acousticness'], unique=False)
        batch_op.create_index(batch_op.f('ix_spotifytrackaudiofeatures_danceability'), ['danceability'], unique=False)
        batch_op.create_index(batch_op.f('ix_spotifytrackaudiofeatures_duration_ms'), ['duration_ms'], unique=False)
        batch_op.create_index(batch_op.f('ix_spotifytrackaudiofeatures_energy'), ['energy'], unique=False)
        batch_op.create_index(batch_op.f('ix_spotifytrackaudiofeatures_instrumentalness'), ['instrumentalness'], unique=False)
        batch_op.create_index(batch_op.f('ix_spotifytrackaudiofeatures_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_spotifytrackaudiofeatures_liveness'), ['liveness'], unique=False)
        batch_op.create_index(batch_op.f('ix_spotifytrackaudiofeatures_mode'), ['mode'], unique=False)
        batch_op.create_index(batch_op.f('ix_spotifytrackaudiofeatures_speechiness'), ['speechiness'], unique=False)
        batch_op.create_index(batch_op.f('ix_spotifytrackaudiofeatures_tempo'), ['tempo'], unique=False)
        batch_op.create_index(batch_op.f('ix_spotifytrackaudiofeatures_time_signature'), ['time_signature'], unique=False)
        batch_op.create_index(batch_op.f('ix_spotifytrackaudiofeatures_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_spotifytrackaudiofeatures_valence'), ['valence'], unique=False)

    with op.batch_alter_table('spotifytrackhistoryaudiofeatures', schema=None) as batch_op:
        batch_op.drop_index('ix_spotifytrackhistoryaudiofeatures_acousticness')
        batch_op.drop_index('ix_spotifytrackhistoryaudiofeatures_danceability')
        batch_op.drop_index('ix_spotifytrackhistoryaudiofeatures_duration_ms')
        batch_op.drop_index('ix_spotifytrackhistoryaudiofeatures_energy')
        batch_op.drop_index('ix_spotifytrackhistoryaudiofeatures_instrumentalness')
        batch_op.drop_index('ix_spotifytrackhistoryaudiofeatures_key')
        batch_op.drop_index('ix_spotifytrackhistoryaudiofeatures_liveness')
        batch_op.drop_index('ix_spotifytrackhistoryaudiofeatures_mode')
        batch_op.drop_index('ix_spotifytrackhistoryaudiofeatures_speechiness')
        batch_op.drop_index('ix_spotifytrackhistoryaudiofeatures_tempo')
        batch_op.drop_index('ix_spotifytrackhistoryaudiofeatures_time_signature')
        batch_op.drop_index('ix_spotifytrackhistoryaudiofeatures_updated_at')
        batch_op.drop_index('ix_spotifytrackhistoryaudiofeatures_valence')

    op.drop_table('spotifytrackhistoryaudiofeatures')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spotifytrackhistoryaudiofeatures',
    sa.Column('spotify_id', sa.VARCHAR(), nullable=False),
    sa.Column('acousticness', sa.FLOAT(), nullable=False),
    sa.Column('danceability', sa.FLOAT(), nullable=False),
    sa.Column('duration_ms', sa.INTEGER(), nullable=False),
    sa.Column('energy', sa.FLOAT(), nullable=False),
    sa.Column('instrumentalness', sa.FLOAT(), nullable=False),
    sa.Column('key', sa.INTEGER(), nullable=False),
    sa.Column('liveness', sa.FLOAT(), nullable=False),
    sa.Column('mode', sa.INTEGER(), nullable=False),
    sa.Column('speechiness', sa.FLOAT(), nullable=False),
    sa.Column('tempo', sa.FLOAT(), nullable=False),
    sa.Column('time_signature', sa.INTEGER(), nullable=False),
    sa.Column('valence', sa.FLOAT(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['spotify_id'], ['spotifytrack.spotify_id'], name='fk_spotifytrackhistoryaudiofeatures_spotify_id_spotifytrack'),
    sa.PrimaryKeyConstraint('spotify_id', name='pk_spotifytrackhistoryaudiofeatures')
    )
    with op.batch_alter_table('spotifytrackhistoryaudiofeatures', schema=None) as batch_op:
        batch_op.create_index('ix_spotifytrackhistoryaudiofeatures_valence', ['valence'], unique=False)
        batch_op.create_index('ix_spotifytrackhistoryaudiofeatures_updated_at', ['updated_at'], unique=False)
        batch_op.create_index('ix_spotifytrackhistoryaudiofeatures_time_signature', ['time_signature'], unique=False)
        batch_op.create_index('ix_spotifytrackhistoryaudiofeatures_tempo', ['tempo'], unique=False)
        batch_op.create_index('ix_spotifytrackhistoryaudiofeatures_speechiness', ['speechiness'], unique=False)
        batch_op.create_index('ix_spotifytrackhistoryaudiofeatures_mode', ['mode'], unique=False)
        batch_op.create_index('ix_spotifytrackhistoryaudiofeatures_liveness', ['liveness'], unique=False)
        batch_op.create_index('ix_spotifytrackhistoryaudiofeatures_key', ['key'], unique=False)
        batch_op.create_index('ix_spotifytrackhistoryaudiofeatures_instrumentalness', ['instrumentalness'], unique=False)
        batch_op.create_index('ix_spotifytrackhistoryaudiofeatures_energy', ['energy'], unique=False)
        batch_op.create_index('ix_spotifytrackhistoryaudiofeatures_duration_ms', ['duration_ms'], unique=False)
        batch_op.create_index('ix_spotifytrackhistoryaudiofeatures_danceability', ['danceability'], unique=False)
        batch_op.create_index('ix_spotifytrackhistoryaudiofeatures_acousticness', ['acousticness'], unique=False)

    with op.batch_alter_table('spotifytrackaudiofeatures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spotifytrackaudiofeatures_valence'))
        batch_op.drop_index(batch_op.f('ix_spotifytrackaudiofeatures_updated_at'))
        batch_op.drop_index(batch_op.f('ix_spotifytrackaudiofeatures_time_signature'))
        batch_op.drop_index(batch_op.f('ix_spotifytrackaudiofeatures_tempo'))
        batch_op.drop_index(batch_op.f('ix_spotifytrackaudiofeatures_speechiness'))
        batch_op.drop_index(batch_op.f('ix_spotifytrackaudiofeatures_mode'))
        batch_op.drop_index(batch_op.f('ix_spotifytrackaudiofeatures_liveness'))
        batch_op.drop_index(batch_op.f('ix_spotifytrackaudiofeatures_key'))
        batch_op.drop_index(batch_op.f('ix_spotifytrackaudiofeatures_instrumentalness'))
        batch_op.drop_index(batch_op.f('ix_spotifytrackaudiofeatures_energy'))
        batch_op.drop_index(batch_op.f('ix_spotifytrackaudiofeatures_duration_ms'))
        batch_op.drop_index(batch_op.f('ix_spotifytrackaudiofeatures_danceability'))
        batch_op.drop_index(batch_op.f('ix_spotifytrackaudiofeatures_acousticness'))

    op.drop_table('spotifytrackaudiofeatures')
    # ### end Alembic commands ###
