"""add MyDiaryImage table

Revision ID: c79067dc46b8
Revises: 76195e4bb3e1
Create Date: 2022-12-18 12:45:28.702332

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'c79067dc46b8'
down_revision = '76195e4bb3e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mydiaryimage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('filepath', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('nextcloud_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('thumbnail_size', sa.Integer(), nullable=False),
    sa.Column('joplin_resource_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mydiaryimage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mydiaryimage_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_mydiaryimage_hash'), ['hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_mydiaryimage_joplin_resource_id'), ['joplin_resource_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mydiaryimage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mydiaryimage_joplin_resource_id'))
        batch_op.drop_index(batch_op.f('ix_mydiaryimage_hash'))
        batch_op.drop_index(batch_op.f('ix_mydiaryimage_created_at'))

    op.drop_table('mydiaryimage')
    # ### end Alembic commands ###
