"""add spotifycontext table

Revision ID: cd57c3c10e94
Revises: 4e69b49f6a0d
Create Date: 2022-04-17 10:53:29.090428

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'cd57c3c10e94'
down_revision = '4e69b49f6a0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spotifycontext',
    sa.Column('uri', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('context_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('context_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('uri')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spotifycontext')
    # ### end Alembic commands ###
