"""sqlite db backup table

Revision ID: e943e3d13add
Revises: 392cf2aec96f
Create Date: 2023-09-30 13:18:37.739905

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'e943e3d13add'
down_revision = '392cf2aec96f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mydiarydatabasebackup',
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('alembic_rev', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hostname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('filename', name=op.f('pk_mydiarydatabasebackup'))
    )
    with op.batch_alter_table('mydiarydatabasebackup', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mydiarydatabasebackup_alembic_rev'), ['alembic_rev'], unique=False)
        batch_op.create_index(batch_op.f('ix_mydiarydatabasebackup_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mydiarydatabasebackup', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mydiarydatabasebackup_created_at'))
        batch_op.drop_index(batch_op.f('ix_mydiarydatabasebackup_alembic_rev'))

    op.drop_table('mydiarydatabasebackup')
    # ### end Alembic commands ###
