"""add owntracks location and day map tables

Revision ID: fac8c0f908eb
Revises: 4f09dd377b15
Create Date: 2026-08-01 17:17:12.235539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'fac8c0f908eb'
down_revision: Union[str, None] = '4f09dd377b15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owntracksdaymap',
    sa.Column('diary_date', sa.Date(), nullable=False),
    sa.Column('joplin_resource_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('num_points', sa.Integer(), nullable=False),
    sa.Column('num_stays', sa.Integer(), nullable=False),
    sa.Column('distance_m', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('diary_date')
    )
    with op.batch_alter_table('owntracksdaymap', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_owntracksdaymap_content_hash'), ['content_hash'], unique=False)

    op.create_table('owntrackslocation',
    sa.Column('tst', sa.DateTime(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('acc', sa.Integer(), nullable=True),
    sa.Column('vac', sa.Integer(), nullable=True),
    sa.Column('alt', sa.Integer(), nullable=True),
    sa.Column('vel', sa.Integer(), nullable=True),
    sa.Column('cog', sa.Integer(), nullable=True),
    sa.Column('batt', sa.Integer(), nullable=True),
    sa.Column('conn', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('trigger', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('motion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ssid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('device', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', 'device', 'tst', name='uix_owntracks_fix')
    )
    with op.batch_alter_table('owntrackslocation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_owntrackslocation_device'), ['device'], unique=False)
        batch_op.create_index(batch_op.f('ix_owntrackslocation_tst'), ['tst'], unique=False)
        batch_op.create_index(batch_op.f('ix_owntrackslocation_username'), ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owntrackslocation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_owntrackslocation_username'))
        batch_op.drop_index(batch_op.f('ix_owntrackslocation_tst'))
        batch_op.drop_index(batch_op.f('ix_owntrackslocation_device'))

    op.drop_table('owntrackslocation')
    with op.batch_alter_table('owntracksdaymap', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_owntracksdaymap_content_hash'))

    op.drop_table('owntracksdaymap')
    # ### end Alembic commands ###
