"""add spelling bee misses, puzzles, and definitions

Revision ID: fd9d21eb39d6
Revises: fac8c0f908eb
Create Date: 2026-08-08 17:28:55.699454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'fd9d21eb39d6'
down_revision: Union[str, None] = 'fac8c0f908eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spellingbeedefinition',
    sa.Column('definition', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('part_of_speech', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('word', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('word')
    )
    with op.batch_alter_table('spellingbeedefinition', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spellingbeedefinition_fetched_at'), ['fetched_at'], unique=False)

    op.create_table('spellingbeemiss',
    sa.Column('puzzle_date', sa.Date(), nullable=False),
    sa.Column('word', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('puzzle_date', 'word', name='uix_spellingbee_miss')
    )
    with op.batch_alter_table('spellingbeemiss', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spellingbeemiss_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_spellingbeemiss_puzzle_date'), ['puzzle_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_spellingbeemiss_word'), ['word'], unique=False)

    op.create_table('spellingbeepuzzle',
    sa.Column('center_letter', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('outer_letters', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('puzzle_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('puzzle_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spellingbeepuzzle')
    with op.batch_alter_table('spellingbeemiss', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spellingbeemiss_word'))
        batch_op.drop_index(batch_op.f('ix_spellingbeemiss_puzzle_date'))
        batch_op.drop_index(batch_op.f('ix_spellingbeemiss_created_at'))

    op.drop_table('spellingbeemiss')
    with op.batch_alter_table('spellingbeedefinition', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spellingbeedefinition_fetched_at'))

    op.drop_table('spellingbeedefinition')
    # ### end Alembic commands ###
