"""add api sync timestamps to pocketarticle and google calendar tables

Revision ID: fe286885f86e
Revises: cc3ed16547a4
Create Date: 2024-12-24 14:34:46.045428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe286885f86e'
down_revision: Union[str, None] = 'cc3ed16547a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('googlecalendarevent', sa.Column('time_last_api_sync', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_googlecalendarevent_time_last_api_sync'), 'googlecalendarevent', ['time_last_api_sync'], unique=False)
    op.add_column('pocketarticle', sa.Column('time_last_api_sync', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_pocketarticle_time_last_api_sync'), 'pocketarticle', ['time_last_api_sync'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pocketarticle_time_last_api_sync'), table_name='pocketarticle')
    op.drop_column('pocketarticle', 'time_last_api_sync')
    op.drop_index(op.f('ix_googlecalendarevent_time_last_api_sync'), table_name='googlecalendarevent')
    op.drop_column('googlecalendarevent', 'time_last_api_sync')
    # ### end Alembic commands ###
