"""separate spotifytrack and spotifytrackhistory tables

Revision ID: ff8fd8da6b6a
Revises: cd57c3c10e94
Create Date: 2022-04-17 11:20:57.319565

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'ff8fd8da6b6a'
down_revision = 'cd57c3c10e94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spotifytrack',
    sa.Column('spotify_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('artist_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('uri', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('played_at', sa.DateTime(), nullable=True),
    sa.Column('context_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('context_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('spotify_id')
    )
    with op.batch_alter_table('spotifytrack', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spotifytrack_artist_name'), ['artist_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_spotifytrack_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_spotifytrack_played_at'), ['played_at'], unique=False)

    with op.batch_alter_table('spotifytrackhistory', schema=None) as batch_op:
        batch_op.drop_index('ix_spotifytrackhistory_artist_name')
        batch_op.drop_index('ix_spotifytrackhistory_name')
        batch_op.drop_index('ix_spotifytrackhistory_spotify_id')
        batch_op.drop_column('uri')
        batch_op.drop_column('context_uri')
        batch_op.drop_column('name')
        batch_op.drop_column('artist_name')
        batch_op.drop_column('context_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spotifytrackhistory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('context_type', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('artist_name', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('context_uri', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('uri', sa.VARCHAR(), nullable=False))
        batch_op.create_index('ix_spotifytrackhistory_spotify_id', ['spotify_id'], unique=False)
        batch_op.create_index('ix_spotifytrackhistory_name', ['name'], unique=False)
        batch_op.create_index('ix_spotifytrackhistory_artist_name', ['artist_name'], unique=False)

    with op.batch_alter_table('spotifytrack', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spotifytrack_played_at'))
        batch_op.drop_index(batch_op.f('ix_spotifytrack_name'))
        batch_op.drop_index(batch_op.f('ix_spotifytrack_artist_name'))

    op.drop_table('spotifytrack')
    # ### end Alembic commands ###
